### ISSUE TITLE
Remove Grayscale panels

### ISSUE THREAD

**Issue by AndrewBelt** [Aepelzen/AepelzensParasites#4]
Did Grayscale approve the use of his panel designs?

If not, the panels need to be replaced with your own original design, as this is an IP violation. I have removed Aepelzens Parasites from the plugins list until this issue is resolved.

**Comment by Aepelzen** [comment]
Seriously? A little heads up would have been nice instead of just removing me from the list.

I did not ask for permission to use the graphics. I considered those a modification of the original work of Mutable Instruments which is licensed under an MIT license (or CC-BY-SA for the graphics). Per license all modifications of those remain free. That's why i used an MIT license for my repository and not GPL as I would normally do. I could add a reference to grayscale though if that is necessary.

**Comment by AndrewBelt** [comment]
A requirement for being listed on the Plugin Manager is that it does not violate IP laws. Grayscale's designs are not modifications of Mutable Instruments panels, since all design elements are original, and positions of knobs are not copyrightable.

I have also noticed some other issues.
- Olivier Gillet has said "We do not recommend you to keep the original name of the Mutable Instruments module for your derivative works." https://github.com/pichenettes/eurorack These need to be removed as well.
- Regarding the large Gate Sequencer in https://github.com/Aepelzen/AepelzensModules, this is a clear derivative work of the Fundamental panels, where "Panel graphics in res/ are © 2017 by Grayscale" https://github.com/VCVRack/Fundamental

Grayscale and I have given the community enormous amounts of software and graphics, and so far everyone has appreciated that and respected the property of others. I ask that you do the same by putting a bit of effort into designing your own panels.

**Comment by Aepelzen** [comment]
First of all let me say that I do appreciate your work and am very grateful for it. I'm not trying to cause any troubles and just want to clarify some things, so I can get them right.

1. I did not know about the name thing and will change them
2. The graphics issue is only about the panels, i can still use the Component Library (knobs etc.), right?
3. The Gate Sequencer is indeed based on the fundamental sequencer. How much would I have to change to not violate any property rights? Because this is a single colored panel with text that does not allow much room for improvisations (it is basically defined by the functionality). If I had to come up with my own "design" it would be pretty much this with a different font (just like my other modules). Would that be enough?

**Comment by AndrewBelt** [comment]
1. Yes, you could get creative like "Tidal Parasite" and "Meta Parasite" or something.
2. Yes, you can use the Component Library graphics since those are licensed under CC BY-NC 4.0.
3. It's up to you, but I think it would be sufficient to make everything on the panel the same font as the text "Gate Sequencer", which would make it look better as well.

**Comment by milholen** [comment]
The "Cycles" panel still uses the Grayscale graphics as the basis, please remove.
